import { Link, useRouterState } from "@tanstack/react-router";
import { Bot, Camera, CloudSun, FlaskConical, Home, Leaf, LogOut, Menu, Settings, Sprout, Store, User, X, type LucideIcon } from "lucide-react";
import { useState, type FormEvent, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { cn } from "@/lib/utils";
import { useAuth } from "@/lib/auth";

export const navItems: { to: string; label: string; icon: LucideIcon }[] = [
  { to: "/dashboard", label: "Home", icon: Home }, { to: "/crop", label: "Crop", icon: Sprout },
  { to: "/plant", label: "Check plant", icon: Camera }, { to: "/fertilizer", label: "Fertilizer", icon: FlaskConical },
  { to: "/weather", label: "Weather", icon: CloudSun }, { to: "/market", label: "Market", icon: Store }, { to: "/assistant", label: "Ask AI", icon: Bot },
];

export function Brand({ compact = false }: { compact?: boolean }) { return <Link to="/" className="inline-flex items-center gap-3 text-foreground"><span className="grid size-10 place-items-center rounded-xl bg-primary text-primary-foreground"><Leaf /></span>{!compact && <span className="font-display text-xl font-bold">AgriVision <span className="text-primary">AI</span></span>}</Link>; }

export function AppShell({ children }: { children: ReactNode }) {
  const [open, setOpen] = useState(false); const path = useRouterState({ select: s => s.location.pathname }); const { user, logout } = useAuth();
  const links = <>{navItems.map(item => <Link key={item.to} to={item.to} onClick={() => setOpen(false)} className={cn("flex min-h-11 items-center gap-3 rounded-lg px-3 text-sm font-semibold transition-colors", path === item.to ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-accent hover:text-accent-foreground")}><item.icon className="size-5" />{item.label}</Link>)}</>;
  return <div className="min-h-screen bg-background"><aside className="fixed inset-y-0 left-0 z-40 hidden w-64 border-r border-border bg-card p-5 lg:flex lg:flex-col"><Brand /><nav className="mt-9 grid gap-1">{links}</nav><div className="mt-auto grid gap-1 border-t border-border pt-4"><Link to="/settings" className="flex min-h-11 items-center gap-3 px-3 text-sm font-semibold text-muted-foreground"><Settings className="size-5"/>Settings</Link><Link to="/profile" className="flex min-h-11 items-center gap-3 px-3 text-sm font-semibold text-muted-foreground"><User className="size-5"/>{user?.name ?? "Profile"}</Link>
  <button
  type="button"
  onClick={logout}
  className="flex min-h-11 w-full cursor-pointer items-center gap-3 rounded-lg px-3 text-left text-sm font-semibold text-muted-foreground hover:bg-accent hover:text-accent-foreground">
  <LogOut className="size-5"/>Logout</button></div></aside><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-border bg-card/95 px-4 backdrop-blur lg:hidden"><Brand /><Button variant="ghost" size="icon" aria-label="Open navigation" onClick={() => setOpen(true)}><Menu/></Button></header>{open && <div className="fixed inset-0 z-50 bg-foreground/30 lg:hidden" onClick={() => setOpen(false)}><aside className="h-full w-[82%] max-w-xs bg-card p-5" onClick={e => e.stopPropagation()}><div className="flex items-center justify-between"><Brand/><Button variant="ghost" size="icon" aria-label="Close navigation" onClick={() => setOpen(false)}><X/></Button></div><nav className="mt-8 grid gap-1">{links}</nav></aside></div>}<main className="mx-auto max-w-6xl px-4 pb-24 pt-6 sm:px-6 lg:ml-64 lg:px-10 lg:pb-12 lg:pt-9">{children}</main><nav className="fixed inset-x-0 bottom-0 z-30 grid grid-cols-5 border-t border-border bg-card px-1 pb-[env(safe-area-inset-bottom)] lg:hidden">{navItems.slice(0,5).map(item => <Link key={item.to} to={item.to} className={cn("flex min-h-16 flex-col items-center justify-center gap-1 text-[11px] font-semibold", path === item.to ? "text-primary" : "text-muted-foreground")}><item.icon className="size-5"/>{item.label}</Link>)}</nav></div>;
}

export function PageHeader({ eyebrow, title, description }: { eyebrow?: string; title: string; description: string }) { return <header className="mb-7"><p className="mb-2 text-xs font-bold uppercase text-primary">{eyebrow}</p><h1 className="text-3xl font-bold sm:text-4xl">{title}</h1><p className="mt-2 max-w-2xl text-muted-foreground">{description}</p></header>; }
export function Panel({ children, className }: { children: ReactNode; className?: string }) { return <section className={cn("surface-card rounded-xl p-5 sm:p-6", className)}>{children}</section>; }
export function Field({ label, hint, error, ...props }: React.ComponentProps<typeof Input> & { label: string; hint?: string; error?: string }) { const id = props.id ?? props.name; return <div className="space-y-2"><Label htmlFor={id}>{label}</Label><Input id={id} className="field-control" {...props}/>{hint && <p className="text-xs text-muted-foreground">{hint}</p>}{error && <p className="text-xs font-semibold text-destructive">{error}</p>}</div>; }
export function NativeSelect({ label, name, value, onChange, options, required = true }: { label: string; name: string; value: string; onChange: React.ChangeEventHandler<HTMLSelectElement>; options: string[]; required?: boolean }) { return <div className="space-y-2"><Label htmlFor={name}>{label}</Label><select id={name} name={name} value={value} onChange={onChange} required={required} className="field-control w-full px-3 text-sm"><option value="">Select {label.toLowerCase()}</option>{options.map(option => <option key={option}>{option}</option>)}</select></div>; }
export function Status({ kind = "loading", title, message }: { kind?: "loading"|"error"|"empty"; title: string; message: string }) { return <div className={cn("rounded-xl border p-5", kind === "error" ? "border-destructive/30 bg-destructive/5" : "border-border bg-muted/50")}><div className="flex gap-3">{kind === "loading" ? <span className="mt-1 size-5 animate-spin rounded-full border-2 border-primary border-t-transparent"/> : <Leaf className="mt-0.5 size-5 text-primary"/>}<div><p className="font-bold">{title}</p><p className="mt-1 text-sm text-muted-foreground">{message}</p></div></div></div>; }
export function Result({ icon: Icon = Leaf, label, value, children, tone = "green" }: { icon?: LucideIcon; label: string; value: string; children?: ReactNode; tone?: "green"|"orange"|"blue"|"purple" }) { return <Panel className={cn("border-l-4", tone === "orange" && "border-l-warning", tone === "blue" && "border-l-weather", tone === "purple" && "border-l-ai", tone === "green" && "border-l-primary")}><div className="flex items-start gap-4"><span className={cn("grid size-12 shrink-0 place-items-center rounded-xl", tone === "blue" ? "bg-weather-soft text-weather" : tone === "purple" ? "bg-ai-soft text-ai" : tone === "orange" ? "bg-warning/15 text-warning" : "bg-leaf-soft text-primary")}><Icon/></span><div><p className="text-sm font-semibold text-muted-foreground">{label}</p><h2 className="mt-1 text-2xl font-bold">{value}</h2></div></div>{children && <div className="mt-5 border-t border-border pt-5">{children}</div>}</Panel>; }
export function useFormSubmit<T>(action: () => Promise<T>, onSuccess: (data: T) => void) { const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const submit=async(e:FormEvent)=>{e.preventDefault();setLoading(true);setError("");try{onSuccess(await action());}catch(err){setError(err instanceof Error?err.message:"Please try again.");}finally{setLoading(false);}}; return {loading,error,submit,setError}; }