/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CropRouteImport } from './routes/crop'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FertilizerRouteImport } from './routes/fertilizer'
import { Route as MarketRouteImport } from './routes/market'
import { Route as PlantRouteImport } from './routes/plant'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WeatherRouteImport } from './routes/weather'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CropRoute = CropRouteImport.update({
  id: '/crop',
  path: '/crop',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FertilizerRoute = FertilizerRouteImport.update({
  id: '/fertilizer',
  path: '/fertilizer',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantRoute = PlantRouteImport.update({
  id: '/plant',
  path: '/plant',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/crop': typeof CropRoute
  '/dashboard': typeof DashboardRoute
  '/fertilizer': typeof FertilizerRoute
  '/market': typeof MarketRoute
  '/plant': typeof PlantRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/weather': typeof WeatherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/crop': typeof CropRoute
  '/dashboard': typeof DashboardRoute
  '/fertilizer': typeof FertilizerRoute
  '/market': typeof MarketRoute
  '/plant': typeof PlantRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/weather': typeof WeatherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/crop': typeof CropRoute
  '/dashboard': typeof DashboardRoute
  '/fertilizer': typeof FertilizerRoute
  '/market': typeof MarketRoute
  '/plant': typeof PlantRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/weather': typeof WeatherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/auth'
    | '/crop'
    | '/dashboard'
    | '/fertilizer'
    | '/market'
    | '/plant'
    | '/profile'
    | '/settings'
    | '/weather'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/auth'
    | '/crop'
    | '/dashboard'
    | '/fertilizer'
    | '/market'
    | '/plant'
    | '/profile'
    | '/settings'
    | '/weather'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/auth'
    | '/crop'
    | '/dashboard'
    | '/fertilizer'
    | '/market'
    | '/plant'
    | '/profile'
    | '/settings'
    | '/weather'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  CropRoute: typeof CropRoute
  DashboardRoute: typeof DashboardRoute
  FertilizerRoute: typeof FertilizerRoute
  MarketRoute: typeof MarketRoute
  PlantRoute: typeof PlantRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  WeatherRoute: typeof WeatherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop': {
      id: '/crop'
      path: '/crop'
      fullPath: '/crop'
      preLoaderRoute: typeof CropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fertilizer': {
      id: '/fertilizer'
      path: '/fertilizer'
      fullPath: '/fertilizer'
      preLoaderRoute: typeof FertilizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plant': {
      id: '/plant'
      path: '/plant'
      fullPath: '/plant'
      preLoaderRoute: typeof PlantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  CropRoute: CropRoute,
  DashboardRoute: DashboardRoute,
  FertilizerRoute: FertilizerRoute,
  MarketRoute: MarketRoute,
  PlantRoute: PlantRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  WeatherRoute: WeatherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
